### ISSUE TITLE
How does Birdsong handle socket reconnects?

### ISSUE THREAD

**Issue by jpettit** [sjrmanning/Birdsong#14]
Are queued messages re-sent upon reconnect?

**Comment by codeOfRobin** [comment]
@jpettit AFAICT(I'm not the maintainer) there's no queuing for messages. As soon as a socket disconnects and you try to send a message, you should receive an error from the callbacks that Starscream sends. Any queueing behaviour on reconnection would have to be handled on your end.

**Comment by sjrmanning** [comment]
Yes that's true. I would prefer clients using Birdsong implement their own behaviour rather than relying on something a bit more of a black-box, as I had issues with other Phoenix socket clients reconnection behaviour. You'll know when an action has succeeded via `Push.receieve`. I'm of course happy to hear suggestions if you feel otherwise though!

**Comment by jpettit** [comment]
Thanks for the info.
